### ISSUE TITLE
Unfamiliar Syntax

### ISSUE THREAD

**Issue by bmzhao** [playframework/play-websocket-java#26]
Sorry for my ignorance, but could someone explain how the syntax on line 38 of StocksActor.java works?

```.<Iterable<ActorRef>>map(Collections::singletonList)```

How can there be a Generic Type `<Iterable<ActorRef>>` after the dot operator and before the map call?

**Comment by gmethvin** [comment]
@bmzhao If you have questions you can ask on the [mailing list](https://groups.google.com/forum/#!forum/play-framework). This tracker is for bugs.

The [`Optional#map`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#map-java.util.function.Function-) function is generic on the new type held by the mapped `Optional`. It is needed because the inferred type from `singletonList()` would be a `List<ActorRef>`, and in the following `orElse` call `getChildren()` returns an `Iterable<ActorRef>`.
